blueprint:
  name: Heizung - Alexa Info Heizung an 
  description: 'Alexa Ansage, wenn die Heizung eingeschaltet wird.'
  domain: automation
  input:
    climate:
      name: Heizung
      selector:
        entity:
    echo_device:
      name: Alexa
      description: Das Alexa-Gerät auf dem die Ansage gemacht werden soll. Erstellen Sie eine durch Kommas getrennte Liste, um sie auf mehreren Geräten wiederzugeben.
      selector:
        entity:
          domain: media_player
    condition:
       name: Bedingung für Echo Wiedergabe (state off)
       default: ''
    message:
      name: Message (Optional)
      description: 'Default: "Die Heizung ist an."'
      default: Die Heizung ist an.
mode: single
trigger:
- platform: state
  entity_id: !input 'climate'
  from: "off"
  to: "heat"
  for: "00:00:05"
condition:
- condition: state
  entity_id: !input 'condition'
  state: 'off'
action:
  - service: notify.alexa_media
    data:
      target:
        - !input 'echo_device'
      message: !input message
      data:
        type: tts
