blueprint:
  name: Fenster offen, Heizung aus
  domain: automation
  input:
    window_entity:
      name: Fenster Sensor
      selector:
        entity:
    climate_target:
      name: Climate Device
      selector:
        entity:
          domain: climate
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 30
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
trigger:
  - platform: state
    entity_id: !input window_entity
    to: 'on'
    for: !input no_motion_wait
condition:
  - condition: state
    entity_id: !input climate_target
    state: 'heat'
action:
  - service: climate.turn_off
    entity_id: !input climate_target
  - wait_for_trigger:
    - platform: state
      entity_id: !input window_entity
      to: 'off'
    continue_on_timeout: false
  - service: climate.turn_on
    entity_id: !input climate_target
