blueprint:
  name: Heizung - Alexa Info
  description: 'Alexa Ansage, wenn die Heizung eingeschaltet wird.'
  domain: automation
  input:
    climate:
      name: Heizung
      selector:
        entity:
    echo_device:
      name: Alexa
      description: Das Alexa-Gerät, auf dem die Ansage gemacht werden soll. Erstellen Sie eine durch Kommas getrennte Liste, um sie auf mehreren Geräten wiederzugeben.
      selector:
        entity:
          domain: media_player
    message:
      name: Message (Optional)
      description: 'Default: "Die Heizung ist aus."'
      default: Die Heizung ist aus.
mode: single
trigger:
- platform: state
  entity_id: !input 'climate'
  from: "heat"
  to: "off"
  for: "00:00:15"
action:
  - service: notify.alexa_media
    data:
      target:
        - !input 'echo_device'
      message: !input message
      data:
        type: tts
