blueprint:
  name: Fenster offen, Heizung aus
  domain: automation
  input:
    window_entity:
      name: Fenster Sensor
      selector:
        entity:
          domain: 
            - binary_sensor
            - group
    climate_target:
      name: Climate Device
      selector:
        entity:
          domain: climate

trigger:
  - platform: state
    entity_id: !input window_entity
    to: 'on'

action:
  - service: climate.turn_off
    entity_id: !input climate_target
  - wait_for_trigger:
    - platform: state
      entity_id: !input window_entity
      to: 'off'
    continue_on_timeout: false
  - service: climate.turn_on
    entity_id: !input climate_target
